
#Machine Energy Usage Config. This config is synced from server to client.
[usage]
	#Energy per operation tick (Joules).
	enrichmentChamber = "50000"
	#Energy per operation tick (Joules).
	osmiumCompressor = "100000"
	#Energy per operation tick (Joules).
	combiner = "50000"
	#Energy per operation tick (Joules).
	crusher = "50000"
	#Energy per operation tick (Joules).
	metallurgicInfuser = "50000"
	#Energy per operation tick (Joules).
	purificationChamber = "200000"
	#Energy per operation tick (Joules).
	energizedSmelter = "50000"
	#Energy per operation tick (Joules).
	digitalMiner = "1000000"
	#Energy per operation tick (Joules).
	electricPump = "100000"
	#Energy that can be transferred at once per charge operation (Joules).
	chargePad = "1024000000"
	#Energy per operation tick (Joules).
	rotaryCondensentrator = "50000"
	#Energy per operation tick (Joules).
	oxidationChamber = "200000"
	#Energy per operation tick (Joules).
	chemicalInfuser = "200000"
	#Energy per operation tick (Joules).
	chemicalInjectionChamber = "400000"
	#Energy per operation tick (Joules).
	precisionSawmill = "50000"
	#Energy per operation tick (Joules).
	chemicalDissolutionChamber = "400000"
	#Energy per operation tick (Joules).
	chemicalWasher = "200000"
	#Energy per operation tick (Joules).
	chemicalCrystallizer = "400000"
	#Energy per operation tick (Joules).
	seismicVibrator = "50000"
	#Energy per operation tick (Joules).
	pressurizedReactionBase = "5000"
	#Energy per operation tick (Joules).
	fluidicPlenisher = "100000"
	#Energy per operation tick (Joules).
	laser = "10000000"
	#Energy per operation tick (Joules).
	formulaicAssemblicator = "100000"
	#Energy per operation tick (Joules).
	modificationStation = "100000"
	#Energy per operation tick (Joules).
	isotopicCentrifuge = "200000"
	#Energy per operation tick (Joules).
	nutritionalLiquifier = "200000"
	#Energy per operation tick (Joules).
	antiprotonicNucleosynthesizer = "100000000"
	#Energy per operation tick (Joules).
	pigmentExtractor = "200000"
	#Energy per operation tick (Joules).
	pigmentMixer = "200000"
	#Energy per operation tick (Joules).
	paintingMachine = "100000"
	#Energy per chunk per tick (Joules).
	dimensionalStabilizer = "5000000"

	#Teleporter
	[usage.teleporter]
		#Base Joules cost for a teleportation.
		teleporterBase = "1000000"
		#Joules per unit of distance travelled during teleportation - sqrt(xDiff^2 + yDiff^2 + zDiff^2).
		teleporterDistance = "10000"
		#Flat additional cost for interdimensional teleportation. Distance is still taken into account minimizing energy cost based on dimension scales.
		teleporterDimensionPenalty = "10000000"

