StartupEvents.registry("item", event => {
    event.create('mek1000:crystal_redstone').tag('mekanism:crystals').displayName("Redstone crystal").tooltip("レッドストーンのおいしい結晶").texture("kubejs:item/crystal_redstone")
    event.create('mek1000:extructed_redstone').tag('mekanism:shards').displayName("Extructed redstone ore").tooltip("ちゅーﾁｭﾁｭ... ちゅーｼｭﾁｭ... ちゅーしゅつずみ。").texture("kubejs:item/soft_redstone")
    event.create('mek1000:softore_redstone').displayName("Soft redstone ore").tooltip("やわらかい（当社比）").texture("kubejs:item/soft_redstone").glow(true)
    event.create('mek1000:crystal_certus_quartz').tag('mekanism:crystals').displayName("Certus Quartz crystal").tooltip("ケルタスクオーツのおいしい結晶... ってこれ完成品じゃないの？").texture("kubejs:item/crystal_redstone")
    event.create('mek1000:extructed_certus_quartz').tag('mekanism:shards').displayName("Extructed Certus Quartz").tooltip("ちゅーﾁｭﾁｭ... ちゅーｼｭﾁｭ... ちゅーしゅつずみ。").texture("kubejs:item/soft_redstone")
    event.create('mek1000:softore_certus_quartz').displayName("Soft Certus Quartz").tooltip("やわらかい（当社比）").texture("kubejs:item/soft_redstone").glow(true)
    event.create('mek1000:crystal_fluorite').tag('mekanism:crystals').displayName("Certus Fluorite").tooltip("蛍石のおいしい結晶... ってこれ完成品よりきれい？").texture("kubejs:item/crystal_redstone")
    event.create('mek1000:extructed_fluorite').tag('mekanism:shards').displayName("Extructed Fluorite").tooltip("抽出だけど... これ硫酸に溶かすんよね？").texture("kubejs:item/soft_redstone")
    event.create('mek1000:softore_fluorite').displayName("Soft Fluorite").tooltip("やわらかい（当社比）").texture("kubejs:item/soft_redstone").glow(true)
    event.create('mek1000:crystal_quartz').tag('mekanism:crystals').displayName("Certus Quartz").tooltip("ネザークオーツのおいしい結晶... おいしそう...").texture("kubejs:item/crystal_redstone")
    event.create('mek1000:extructed_quartz').tag('mekanism:shards').displayName("Extructed Quartz").tooltip("抽出・on!").texture("kubejs:item/soft_redstone")
    event.create('mek1000:softore_quartz').displayName("Soft Quartz").tooltip("やわらかい（当社比）").texture("kubejs:item/soft_redstone").glow(true)
})